### ISSUE TITLE
Issue when using bioformats2raw from within python script

### ISSUE THREAD

**Issue by sebi06** [glencoesoftware/bioformats2raw#63] opened 2020-10-12 16:10 UTC
I try to run bioformats2raw from with a python script but git stuck with errors. I am using the following command

```python
print('Use CMD-String : ', cmdstring_bf2raw)

# run the bfconvert tool with the specified parameters
wdir = os.getcwd()
os.chdir(os.path.join(wdir, bf2raw_dir))
print(os.getcwd())
os.system(cmdstring_bf2raw)
```
This results in the following error. Any idea what my mistake here is?

```bash
Uses CMD-String :  bioformats2raw "C:\Temp\input\OverViewScan_8Brains.czi" "C:\Temp\input\OverViewScan_8Brains" --resolutions 4 compression=raw
C:\Users\m1srh\Documents\Apeer_Modules\create_pyramidal_tiff_0ec109bd-6b11-4114-b2b6-b9cfec06d028\bioformats2raw\bin
The input line is too long.
The syntax of the command is incorrect.
````

**Comment by melissalinkert** [comment] 2020-10-12 16:56
Does changing ```compression=raw``` to ```--compression=raw``` still result in an error message?

**Comment by sebi06** [comment] 2020-10-13 07:50
Not really. Now my output is as below. I run this on Windows 10 system.

```bash
Original ImageFile :  C:\Temp\input\OverViewScan_8Brains
ImageFile OME.TIFF :  C:\Temp\input\OverViewScan_8Brains.ome.tiff
Use CMD-1 :  bioformats2raw "C:\Temp\input\OverViewScan_8Brains.czi" "C:\Temp\input\OverViewScan_8Brains" --resolutions 4 --compression=raw
Use CMD-2 :  raw2ometiff "C:\Temp\input\OverViewScan_8Brains" "C:\Temp\input\OverViewScan_8Brains.ome.tiff" --compression=LZW
C:\Users\m1srh\Documents\Apeer_Modules\create_pyramidal_tiff_0ec109bd-6b11-4114-b2b6-b9cfec06d028\bioformats2raw\bin
The input line is too long.
The syntax of the command is incorrect.
C:\Users\m1srh\Documents\Apeer_Modules\create_pyramidal_tiff_0ec109bd-6b11-4114-b2b6-b9cfec06d028\raw2ometiff\bin
The input line is too long.
The syntax of the command is incorrect.
```

The respective python code is below. Maybe it contains a bug?

```python
# create cmdstring for bioformats2raw - mind the spaces !!!
cmdstring_bf2raw = 'bioformats2raw' + ' "' + imagefilepath + '" "' + imgpath_woext + '"' + ' --resolutions ' + str(pyramid_levels) + ' --compression=raw'

# create cmdstring for raw2ometiff - mind the spaces !!!
cmdstring_raw2ometiff = 'raw2ometiff' + ' "' + imgpath_woext + '" "' + file_ometiff + '"' + ' --compression=' + compression

print('Original ImageFile : ', imgpath_woext)
print('ImageFile OME.TIFF : ', file_ometiff)
print('Use CMD-1 : ', cmdstring_bf2raw)
print('Use CMD-2 : ', cmdstring_raw2ometiff)

# run the tools with the specified parameters
wdir = os.getcwd()
os.chdir(os.path.join(wdir, bf2raw_dir))
print(os.getcwd())
os.system(cmdstring_bf2raw)

os.chdir(os.path.join(wdir, raw2ometiff_dir))
print(os.getcwd())
os.system(cmdstring_raw2ometiff)
```

**Comment by chris-allan** [comment] 2020-10-30 10:01
@sebi06: I'm pretty sure what that's signalling is that the command line is too long. All I can suggest is to add the `bioformats2raw` and `raw2ometiff` binaries to your `PATH` before execution if you do not already. Furthermore, you may need to adjust your CWD when executing your Python script in order to avoid the long paths in the first place.

See also #14.

**Comment by sebi06** [comment] 2020-11-04 09:25
Hi Chris, I tried your suggestions but no success so far. I added the location to PATH and also change the CWD before executing the command. Maybe the folder, where `bioformats2raw` is located itself has a too long path?

`C:\Users\m1srh\Documents\Apeer_Modules\create_pyramidal_tiff_0ec109bd-6b11-4114-b2b6-b9cfec06d028\bioformats2raw\bin\bioformats2raw`

Here is the code part I use now:

```python
bf2raw_dir = os.path.abspath(r"bioformats2raw\bin\bioformats2raw")
raw2ome_dir = os.path.abspath(r"raw2ometiff\bin\raw2ometiff")

print("Path bioformats2raw : ", bf2raw_dir)
print("Path raw2ometiff : ", raw2ome_dir)

# add paths
os.environ["PATH"] += os.pathsep + os.pathsep.join([bf2raw_dir, raw2ome_dir])

czifile = r"C:\Temp\input\OverViewScan_8Brains.czi"
tmpfolder = get_fpath_woext(czifile)

# change working directory
os.chdir(os.path.dirname(bf2raw_dir))

# run command
cmd = 'bioformats2raw ' + '"' + czifile + '" ' + '"' + tmpfolder + '"' + ' --resolutions 4 --compression=raw'
print('Command String : ', cmd)
print("Working Directory : ", os.getcwd())
os.system(cmd)
```

And this is the output:

```txt
C:\Users\m1srh\Documents\Apeer_Modules\create_pyramidal_tiff_0ec109bd-6b11-4114-b2b6-b9cfec06d028> cmd /C "C:\ProgramData\Anaconda3\envs\stardist\python.exe c:\Users\m1srh\.vscode\extensions\ms-python.python-2020.10.332292344\pythonFiles\lib\python\debugpy\launcher 63008 -- c:\Users\m1srh\Documents\Apeer_Modules\create_pyramidal_tiff_0ec109bd-6b11-4114-b2b6-b9cfec06d028\test_cmd.py "  
Path bioformats2raw :  C:\Users\m1srh\Documents\Apeer_Modules\create_pyramidal_tiff_0ec109bd-6b11-4114-b2b6-b9cfec06d028\bioformats2raw\bin\bioformats2raw
Path raw2ometiff :  C:\Users\m1srh\Documents\Apeer_Modules\create_pyramidal_tiff_0ec109bd-6b11-4114-b2b6-b9cfec06d028\raw2ometiff\bin\raw2ometiff
Command String :  bioformats2raw "C:\Temp\input\OverViewScan_8Brains.czi" "C:\Temp\input\OverViewScan_8Brains" --resolutions 4 --compression=raw
Working Directory :  C:\Users\m1srh\Documents\Apeer_Modules\create_pyramidal_tiff_0ec109bd-6b11-4114-b2b6-b9cfec06d028\bioformats2raw\bin
The input line is too long.
The syntax of the command is incorrect.
```

**Comment by manics** [comment] 2020-11-04 11:10
> Maybe the folder, where bioformats2raw is located itself has a too long path?

That's quite likely, as Chris already mentioned see https://github.com/glencoesoftware/bioformats2raw/issues/14 for the workarounds

**Comment by melissalinkert** [comment] 2022-03-15 19:26
Closing, as this is assumed to be a duplicate of #14 (for which we don't yet have a long-term solution).

**Closed by melissalinkert** 2022-03-15 19:26 UTC
