### ISSUE TITLE
don't add extra dimensions

### ISSUE THREAD

**Issue by d-v-b** [glencoesoftware/bioformats2raw#209] opened 2023-06-23 19:20 UTC
When I used this tool with a 3D tiff, the resulting zarr arrays had singleton T and C dimensions added. My data is a 3D segmentation image; it has no time axis, and it doesn't have channels. Would it be possible to either refrain from adding extra dimensions or provide a flag to disable this behavior?

**Comment by melissalinkert** [comment] 2023-06-26 15:05
Transferred from [NGFF-Converter](https://github.com/glencoesoftware/NGFF-Converter) to [bioformats2raw](https://github.com/glencoesoftware/bioformats2raw), as NGFF-Converter uses bioformats2raw internally to perform conversion.

Closing as a duplicate of #180. As mentioned there, this isn't possible at the moment, and not something we're likely to implement soon. We'd be happy to look at a pull request if this is a high priority.

**Closed by melissalinkert** 2023-06-26 15:05 UTC
